Alicja 25 synchronizing jupyterhub versions
esa-esdl/jupyterhub-swarm pull request #28
Opened 2019-08-20 13:54 UTC by AliceBalfanz

2019-08-21 12:56 UTC, AliceBalfanz commented
@dzelge, what shall we do with the one failing test?

2019-08-21 12:58 UTC, dzelge commented
Ich schaue mal. Aber der ist dreimal durchgelaufen. Meine Vermutung ist, dass die MPI Leute da drin rumgefummelt hatten.

 

------------------------

Helge

Brockmann Consult

 

Von: Alicja Balfanz <notifications@github.com> 
Gesendet: Mittwoch, 21. August 2019 14:56
An: esa-esdl/jupyterhub-swarm <jupyterhub-swarm@noreply.github.com>
Cc: Helge Dzierzon <helge.dzierzon@brockmann-consult.de>; Mention <mention@noreply.github.com>
Betreff: Re: [esa-esdl/jupyterhub-swarm] Alicja 25 synchronizing jupyterhub versions (#28)

 

@dzelge <https://github.com/dzelge> , what shall we do with the one failing test?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/esa-esdl/jupyterhub-swarm/pull/28?email_source=notifications&email_token=AKDZYIJHEICMWVW226WDYWDQFU3OFA5CNFSM4INXBG7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4ZSBOQ#issuecomment-523444410> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AKDZYIO6EUNJ3VADCPUT7DDQFU3OFANCNFSM4INXBG7A> .  <https://github.com/notifications/beacon/AKDZYIPMS72TYSV3HF4XT6TQFU3OFA5CNFSM4INXBG7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4ZSBOQ.gif>

2019-08-21 12:59 UTC, dzelge commented
In ihrem Julia rumgefummelt hatten während Du das gebaut hast. Die sind nicht soi strikt mit den Versionen

 

------------------------

Helge

Brockmann Consult

 

Von: Alicja Balfanz <notifications@github.com> 
Gesendet: Mittwoch, 21. August 2019 14:56
An: esa-esdl/jupyterhub-swarm <jupyterhub-swarm@noreply.github.com>
Cc: Helge Dzierzon <helge.dzierzon@brockmann-consult.de>; Mention <mention@noreply.github.com>
Betreff: Re: [esa-esdl/jupyterhub-swarm] Alicja 25 synchronizing jupyterhub versions (#28)

 

@dzelge <https://github.com/dzelge> , what shall we do with the one failing test?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/esa-esdl/jupyterhub-swarm/pull/28?email_source=notifications&email_token=AKDZYIJHEICMWVW226WDYWDQFU3OFA5CNFSM4INXBG7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4ZSBOQ#issuecomment-523444410> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AKDZYIO6EUNJ3VADCPUT7DDQFU3OFANCNFSM4INXBG7A> .  <https://github.com/notifications/beacon/AKDZYIPMS72TYSV3HF4XT6TQFU3OFA5CNFSM4INXBG7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4ZSBOQ.gif>

2019-08-21 13:18 UTC, meggart commented
Which test exactly is failing?

2019-08-21 13:23 UTC, dzelge commented
> Which test exactly is failing?

Not a test. One build. But it's OK now

2019-08-22 13:36 UTC, dzelge requested changes
Kannst Du noch in das CHANGELOG reinschreiben, was Du gemacht hast?

2019-08-23 09:25 UTC, merged